# Generated by Django 6.1 on 2026-08-23 21:20

import django.db.models.deletion
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_appuser_profile_picture'),
        ('s3', '0002_blob_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='s3.blob')),
            ],
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('product', 'Product'), ('gallery', 'Gallery'), ('slideshow', 'Slideshow')], max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('style', models.JSONField(default=dict, validators=[store.validators.validate_page_block_style])),
                ('layout', models.JSONField(default=dict, validators=[store.validators.validate_page_block_layout])),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='store.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('theme', models.CharField(choices=[('minimalist', 'Minimalist'), ('professional', 'Professional'), ('artist', 'Artist'), ('contemporary', 'Contemporary'), ('timeless', 'Timeless')], default='minimalist', max_length=255)),
                ('style', models.JSONField(default=dict, validators=[store.validators.validate_style])),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='s3.blob')),
                ('homepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.page')),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='s3.blob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storefronts', to='accounts.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='store.storefront'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug', 'storefront'], name='store_page_slug_fb2e05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug', 'storefront')},
        ),
    ]
