# Generated by Django 6.1 on 2026-08-24 16:49

import store.models
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_blob_expires_at'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='page',
            name='store_page_slug_fb2e05_idx',
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='layout',
            field=models.JSONField(validators=[store.validators.validate_page_block_layout]),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='style',
            field=models.JSONField(default=store.models.default_storefront_style, validators=[store.validators.validate_style]),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['storefront', 'slug'], name='store_page_storefr_60a68f_idx'),
        ),
    ]
