# Generated by Django 6.1 on 2026-08-28 17:39

import django.db.models.deletion
import store.models
import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0003_alter_blob_key'),
        ('store', '0002_remove_page_store_page_slug_fb2e05_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefront',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='s3.blob'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='style',
            field=models.JSONField(default=store.models.default_page_block_style, validators=[store.validators.validate_page_block_style]),
        ),
    ]
