# Generated by Django 6.1 on 2026-08-29 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('store', '0003_storefront_is_draft_alter_page_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='products.product'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('product', 'Product'), ('gallery', 'Gallery'), ('slideshow', 'Slideshow'), ('link', 'Link')], max_length=255),
        ),
    ]
