# Generated by Django 6.1 on 2026-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['stripe_account_id', 'processed_at'], name='billing_str_stripe__6dbf42_idx'), models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['created_at'], name='idx_stripe_event_unprocessed')],
            },
        ),
    ]
