# Generated by Django 6.1 on 2026-09-20 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailverification_expires_at'),
        ('billing', '0001_initial'),
        ('products', '0004_plan_uniq_plan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('cad', 'CAD')], max_length=3)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_subscription_item_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('paused', 'Paused')], max_length=32)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('cad', 'CAD')], max_length=3)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('plan_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.plan')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='billing.subscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-created_at'], name='billing_pay_custome_ab77ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id__isnull', False)), fields=('stripe_checkout_session_id',), name='uniq_payment_checkout_session'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_payment_intent_id__isnull', False)), fields=('stripe_payment_intent_id',), name='uniq_payment_intent'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_invoice_id__isnull', False)), fields=('stripe_invoice_id',), name='uniq_payment_invoice'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('stripe_checkout_session_id__isnull', False), ('stripe_payment_intent_id__isnull', False), ('stripe_invoice_id__isnull', False), _connector='OR'), name='payment_has_a_stripe_id'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer', 'status'], name='billing_sub_custome_8375ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'trialing', 'past_due', 'unpaid'])), fields=('customer', 'plan'), name='uniq_subscription_customer_plan_live'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='billing_ord_custome_382e61_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['subscription', '-created_at'], name='billing_ord_subscri_8a0483_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_quantity_positive'),
        ),
    ]
