# Generated by Django 6.1 on 2026-09-22 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailverification_expires_at'),
        ('billing', '0003_subscription_product_over_capacity'),
        ('products', '0004_plan_uniq_plan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_checkouts', to='accounts.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='products.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='billing_sub_expires_254de0_idx')],
                'unique_together': {('customer', 'plan')},
            },
        ),
    ]
