# Generated by Django 6.1 on 2026-08-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
