# Generated by Django 6.1 on 2026-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_card_payments_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_email',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_seller_user',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='card_payments_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('restricted', 'Restricted'), ('unsupported', 'Unsupported')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_pm_brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('seller', 'email'), name='uniq_customer_seller_email'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('seller', 'user'), name='uniq_customer_seller_user'),
        ),
    ]
