# Generated by Django 6.1 on 2026-09-13 06:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customer_unique_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.default_expiration_time),
        ),
    ]
