# Generated by Django 6.1 on 2026-08-21 21:04

import django.core.validators
import django.db.models.deletion
import s3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_appuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.FileField(upload_to=s3.models.blob_upload_path)),
                ('confirmed', models.BooleanField(default=False)),
                ('checksum', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('byte_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10485760)])),
                ('metadata', models.JSONField(default=dict)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
