# Generated by Django 6.1 on 2026-08-21 23:02

import s3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=s3.models.default_expires_at),
        ),
    ]
