# Generated by Django 6.1 on 2026-08-28 15:32

import s3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0002_blob_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='key',
            field=models.FileField(max_length=512, upload_to=s3.models.blob_upload_path),
        ),
    ]
