# Generated by Django 6.1 on 2026-09-22 01:13

from django.db import migrations


def drop_subscription_items(apps, schema_editor):
    """Subscriptions are bought directly now, so a cart can no longer hold one.

    Destructive, but leaving them is not the safer option: CartItem.clean refuses them
    from here on, so such a cart could be neither edited nor checked out. That defers the
    failure onto the buyer instead of avoiding it.
    """
    CartItem = apps.get_model('cart', 'CartItem')
    CartItem.objects.filter(plan__product__is_subscription=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_reservation_expires_at_and_more'),
    ]

    operations = [
        # Irreversible by design: the reverse would have to invent which plans were in
        # which cart, and an empty reverse would silently claim it had restored them.
        migrations.RunPython(drop_subscription_items, migrations.RunPython.noop),
        # Capacity is now reserved on billing.SubscriptionCheckout, since only
        # subscriptions consume it and they no longer pass through a cart.
        migrations.RemoveField(
            model_name='cart',
            name='reservation_expires_at',
        ),
    ]
