# Generated by Django 6.1 on 2026-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_plan_stripe_price_id_plan_stripe_product_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_price_id__isnull', False)), fields=('stripe_price_id',), name='uniq_plan_stripe_price_id'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_product_id__isnull', False)), fields=('stripe_product_id',), name='uniq_plan_stripe_product_id'),
        ),
    ]
